name: GitHub Actions Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    # 只在下列文件变更时触发
    paths:
      - 'packages/**/CHANGELOG.md'
      - 'legacy/**/*.user.ts'

# 设置权限
permissions: write-all

jobs:
  bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Run Script
        run: pnpm install && pnpm build

      - name: Copy files
        run: cp README.md ./dist/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
